package localizationsource

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/Vyachean/kcd2-dual-subtitles/internal/localization"
)

func TestResolveFromModsRootAcceptsOfficialAnythingModIDLocalizationFilename(t *testing.T) {
	modsRoot := t.TempDir()
	writeLocalizationMod(t, modsRoot, "arbitrary", "arbitrary", "Arbitrary", "English_xml.pak", map[string]string{
		"quests_and_dialogue_arbitrary.xml": dialogueXML(
			localization.DialogueRow{ID: "ui_unrelated", Source: "ui", Text: "must stay outside dialogue"},
			localization.DialogueRow{ID: "dialogue", Source: "mod", Text: "official arbitrary-prefix correction"},
		),
	})

	result, err := resolveFromModsRoot(
		[]localization.DialogueRow{{ID: "dialogue", Source: "stock", Text: "stock"}},
		modsRoot,
		"English_xml.pak",
	)
	if err != nil {
		t.Fatalf("resolveFromModsRoot() error = %v", err)
	}
	if len(result.Rows) != 1 || result.Rows[0].Text != "official arbitrary-prefix correction" {
		t.Fatalf("rows = %+v, want only corrected known dialogue", result.Rows)
	}
	if len(result.Contributions) != 1 || result.Contributions[0].ModID != "arbitrary" {
		t.Fatalf("contributions = %+v, want arbitrary", result.Contributions)
	}
}

func TestResolveFromModsRootIgnoresGenericLocalizationFilenameForDifferentExplicitModID(t *testing.T) {
	modsRoot := t.TempDir()
	writeLocalizationMod(t, modsRoot, "owner", "owner", "Owner", "English_xml.pak", map[string]string{
		"anything_some_other_mod.xml": dialogueXML(
			localization.DialogueRow{ID: "dialogue", Source: "wrong", Text: "must not be attributed to owner"},
		),
	})

	stock := []localization.DialogueRow{{ID: "dialogue", Source: "stock", Text: "stock"}}
	result, err := resolveFromModsRoot(stock, modsRoot, "English_xml.pak")
	if err != nil {
		t.Fatalf("resolveFromModsRoot() error = %v", err)
	}
	if len(result.Rows) != 1 || result.Rows[0] != stock[0] || len(result.Contributions) != 0 {
		t.Fatalf("result = %+v, want unchanged stock and no contribution", result)
	}
}

func TestResolveFromModsRootAcceptsGenericLocalizationWhenManifestModIDIsAutoGenerated(t *testing.T) {
	modsRoot := t.TempDir()
	writeLocalizationMod(t, modsRoot, "generated", "temporary", "Generated Name", "English_xml.pak", map[string]string{
		"arbitrary_generated_name.xml": dialogueXML(
			localization.DialogueRow{ID: "dialogue", Source: "mod", Text: "auto-id correction"},
		),
	})
	manifestPath := filepath.Join(modsRoot, "generated", "mod.manifest")
	manifest := `<?xml version="1.0"?><kcd_mod><info><name>Generated Name</name></info></kcd_mod>`
	if err := os.WriteFile(manifestPath, []byte(manifest), 0o600); err != nil {
		t.Fatal(err)
	}

	result, err := resolveFromModsRoot(
		[]localization.DialogueRow{{ID: "dialogue", Source: "stock", Text: "stock"}},
		modsRoot,
		"English_xml.pak",
	)
	if err != nil {
		t.Fatalf("resolveFromModsRoot() error = %v", err)
	}
	if len(result.Rows) != 1 || result.Rows[0].Text != "auto-id correction" {
		t.Fatalf("rows = %+v, want auto-id correction", result.Rows)
	}
	if len(result.Contributions) != 1 || result.Contributions[0].Name != "Generated Name" {
		t.Fatalf("contributions = %+v, want Generated Name", result.Contributions)
	}
}
